export const serverUrl = "http://localhost:9090"
export const playlistApi = "playlist"
export const albumApi = "albums"
export const userLoginApi = "user/login"
export const userSignupApi = "user"
export const dashboardApi = "dashboard"
export const createPlaylistEmpty = "user_playlists"
export const songsApi = "songs"
export const FavouriteApi = "favourite"
export const HistoryApi = "user_histories"

